### PR TITLE
Create Geographically distributed groups

### LINKED ISSUE #58: Create multiple systems given total capacity, system size and average distance between plants
Perhaps this generates new systems within a Group (#56) . User should enter total desired capacity, the capacity of constituent plants, and average distance. We should generate systems in a new group and use a naming convention to relate them.

Some ideas:
- Should we pre-populate plant sizes for the user? E.G. something like 1000MW total results in ['100MW - 10 sites', '200MW - 5 sites',... etc.] Hard to determine appropriate limits. This would avoid needing to get the plant capacities right to avoid remainders. That could be a non-issue though.
- Is this a feature where it's important to retain the method of creation for these systems? E.g. Do we want to be able to come back, adjust the total capacity/average distance/plant size and recompute?

### PR DESCRIPTION
**Pull request by lboeman**
Adds ability to define groups of systems using Total AC Power, Number of Systems and average distance in km. 
closes #58

### CODE REVIEW

**Comment by PatrickBunn** [comment]
Notes from testing:
- When creating a distributed group, I can't modify the location after the initial click to put it on the map. Maybe I'm not doing it right, but the only way I can relocate a distributed group is to hit the Groups tab and start again.
- Similar to before, on the Update Group page for sites with single-axis tracking under the Tracking heading I still get the site name, rather than tracking type. I think it's been fixed everywhere else though.
- Consider adding a button to queue and compute all sites in a group at once for each year.

**Comment by lboeman** [comment]
>     * When creating a distributed group, I can't modify the location after the initial click to put it on the map. Maybe I'm not doing it right, but the only way I can relocate a distributed group is to hit the Groups tab and start again.

This is more confusing than I had hoped. I think there are two solutions here:
1. Move all of the distributed sites in sync with one another, this might be kind of hard to pull off.
2. Have a "Replace systems" button that just removes all of the systems from the map.
Do you think the second option is good enough?

**Comment by PatrickBunn** [comment]
Yes, the second option was what I was thinking. As long as the inputted parameters stay filled, users can resite with the "Replace Systems"/"Resite Systems" button you suggest.

Just realized this is for all new systems, not just grouped ones

**Comment by lboeman** [comment]
> Yes, the second option was what I was thinking. As long as the inputted parameters stay filled, users can resite with the "Replace Systems"/"Resite Systems" button you suggest.
> 
> Just realized this is for all new systems, not just grouped ones

Hmm, you should be able to click and drag a single system on the map. does that not work for you?

**Comment by PatrickBunn** [comment]
> 

you're right. I wasn't doing it correctly

**Comment by lboeman** [comment]
@PatrickBunn I think I addressed your feedback, when you have time could you take another look?

**Comment by PatrickBunn** [comment]
Testing notes:
- all the new features work!
- consider adding rounding to the distributed capacities when it's not an even split. I did 100 MW over 6 sites:
image
- when looking at individual sites that were generated using the distributed group functionality, I think there's a small bug because the results for each year don't change but the text and Title do.

**Comment by lboeman** [comment]
@PatrickBunn This should be ready for another review when you have time.

**Review by PatrickBunn — APPROVED** [review]

**Pull request merged**
